---
version: '3'

services:
  db:
    image: postgres
    volumes:
      - ates:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=task_tracker
      - POSTGRES_USER=ates
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"

volumes:
  ates:
